version: '3.5'

services:

  flatdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: flats
    ports:
      - 5432:5432

  flatrabbit:
    restart: always
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_NODENAME: "flatrabbit"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"

  flatapp:
    image: flatapp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./flatapp:/var/app/flatapp
    environment:
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_HOST: "flatdb"
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}
      ENTRYPOINT_SCRIPT: "entrypoint.sh"
      SQLALCHEMY_DATABASE_URI: "postgresql://${PG_USER}:${PG_PASS}@flatdb/flats"
    ports:
      - 8000:8000
    depends_on:
      -  flatdb


  flatcelery:
    image: flatcelery
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./flatapp:/var/app/flatapp
    environment:
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_HOST: "flatdb"
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}
      SQLALCHEMY_DATABASE_URI: "postgresql://${PG_USER}:${PG_PASS}@flatdb/flats"
      ENTRYPOINT_SCRIPT: "entrypoint_celery.sh"
    ports:
        - "5555:5555"
    depends_on:
        - flatrabbit
        - flatdb