# Generated by Django 3.2 on 2021-06-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='flat_address',
            field=models.TextField(null=True),
        ),
    ]
