# Generated by Django 3.2 on 2021-06-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_alter_flat_flat_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metertype',
            name='meter_type_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='provider_type_params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
