# Generated by Django 3.2 on 2021-06-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_auto_20210601_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='metervalues',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metervalues',
            name='mv_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
