# Generated by Django 3.2 on 2021-06-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_auto_20210602_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metervalues',
            old_name='synced',
            new_name='mv_synced',
        ),
    ]
